### PR TITLE
Halloween2018

### PR DESCRIPTION
**Pull request by u-nel**
Merge

### CODE REVIEW

**Comment by devcnn88** [comment]
I appreciate the effort you putting in. However, I have question.
Any reason to get headerElement by always assuming it is new UI? I believe there is still people using old UI.

**Comment by u-nel** [comment]
I am using the Old UI and it showing up.

**Comment by u-nel** [comment]
I have fixed the code for it. I am still using the old UI now. And It was included in this pull request.

**Comment by devcnn88** [comment]
Hi @u-nel, since i dont have free time to develop the script anymore, can u share some comment on this issue - https://github.com/devcnn88/MHAutoBotEnhanced/issues/12?
It seems like people unable to hunt normally.
If we unable to fix this issue then Im gonna revert https://github.com/devcnn88/MHAutoBotEnhanced/commit/7d9341d0901e61cf3c66420e233468007586d1c8

**Pull request merged**
